apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-service
  template:
    metadata:
      labels:
        app: backup-service
    spec:
      containers:
      - name: backup-service
        image: cc-project-backup:latest
